### ISSUE TITLE
Arduino libraries

### ISSUE THREAD

**Issue by bmeneguele** [cryptotronix/cryptoauth-arduino#5]
Hello, I am on Linux trying to run the random example of your source code, but I receive the error:

`cryptoauth_test.cpp.o: In function '_GLOBAL__sub_D_sha':`
`/usr/share/arduino/cryptoauth_test.ino:5: undefined reference to 'AtSha204::enableDebug(Stream*)'`
`/usr/share/arduino/cryptoauth_test.ino:5: undefined reference to 'AtEcc108::getRandom(bool)'`
`/usr/share/arduino/cryptoauth_test.ino:5: undefined reference to 'CryptoBuffer::dumpHex(Stream*)'`
`/usr/share/arduino/cryptoauth_test.ino:5: undefined reference to 'AtEcc108::AtEcc108()'`
`/usr/share/arduino/cryptoauth_test.ino:5: undefined reference to 'AtEcc108::~AtEcc108()'`
`collect2: error: ld returned 1 exit status`

I kept all library structure in my ~/arduino/libraries/CryptoAuth, just changed to CryptoAuth.h:

`> ls`
`api  atecc108-atmel  atsha204-atmel  common-atmel  CryptoAuth.h  keywords.txt  softcrypto`

Do you know what could be the problem?
Thank you very much.

**Comment by bmeneguele** [comment]
Forget! I imported your lib in a old fashion (earlier Arduino versions). Everything is working perfectly fine. 
Thank you very much.

**Comment by dandavid3000** [comment]
I got the same problem on both Linux, and Windows. How did you solve this ?

Thank you.

**Comment by bmeneguele** [comment]
Just clone this repository and import it with the new Plugin Manager that Arduino's IDE has. I was trying to copy manually the plugin files.

**Comment by dandavid3000** [comment]
Which version of Arduino IDE, and OS are you using?

Thanks

**Comment by bmeneguele** [comment]
Arduino 1.6.x (I used more than one version) and I tried either on Ubuntu 15.04 and OpenSUSE Tumbleweed.

**Comment by dandavid3000** [comment]
@bmeneguele Thank you. It's working now :)

**Comment by bmeneguele** [comment]
@dandavid3000 good luck :-)
